import static Fgeneral.Fgeneral.artificio;
import java.awt.event.*;  
import javax.swing.*;   
import java.lang.Math;
import javax.swing.ImageIcon;

public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFes = new javax.swing.JLabel();
        jLabelIco = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion = new javax.swing.JLabel();
        textoA = new javax.swing.JTextField();
        variablexc = new javax.swing.JLabel();
        variableyc = new javax.swing.JLabel();
        variablex = new javax.swing.JLabel();
        variabley = new javax.swing.JLabel();
        textoC = new javax.swing.JTextField();
        textoD = new javax.swing.JTextField();
        textoE = new javax.swing.JTextField();
        textoF = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        egeneral = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        igual = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unam.png"))); // NOI18N
        getContentPane().add(jLabelFes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, -1));

        jLabelIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fes.png"))); // NOI18N
        getContentPane().add(jLabelIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelTitulo.setText("IDENTIFICACIÓN DE CÓNICAS");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabelInstruccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelInstruccion.setForeground(new java.awt.Color(240, 240, 240));
        jLabelInstruccion.setText("Ingrese los valores de la ecuación:");
        getContentPane().add(jLabelInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 320, -1));

        textoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAActionPerformed(evt);
            }
        });
        getContentPane().add(textoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 40, -1));

        variablexc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        variablexc.setForeground(new java.awt.Color(240, 240, 240));
        variablexc.setText("X²+");
        getContentPane().add(variablexc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        variableyc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        variableyc.setForeground(new java.awt.Color(240, 240, 240));
        variableyc.setText("Y²+");
        getContentPane().add(variableyc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        variablex.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        variablex.setForeground(new java.awt.Color(240, 240, 240));
        variablex.setText("X+");
        getContentPane().add(variablex, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        variabley.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        variabley.setForeground(new java.awt.Color(240, 240, 240));
        variabley.setText("Y+");
        getContentPane().add(variabley, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        textoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCActionPerformed(evt);
            }
        });
        getContentPane().add(textoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 40, -1));

        textoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDActionPerformed(evt);
            }
        });
        getContentPane().add(textoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 40, -1));

        textoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEActionPerformed(evt);
            }
        });
        getContentPane().add(textoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 40, -1));

        textoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFActionPerformed(evt);
            }
        });
        getContentPane().add(textoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 40, -1));

        boton.setBackground(new java.awt.Color(0, 51, 204));
        boton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton.setForeground(new java.awt.Color(240, 240, 240));
        boton.setText("Introducir valores");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        egeneral.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        egeneral.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(egeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 820, 30));

        resultado.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 570, 310));

        igual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        igual.setForeground(new java.awt.Color(240, 240, 240));
        igual.setText("=0");
        getContentPane().add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 170, 170));
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 170, 170));
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 250, 170));
        getContentPane().add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, 180, 170));
        getContentPane().add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 280, 190));
        getContentPane().add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 310, 320));

        jButton1.setText("Acerca de nosotros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 140, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir (2).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        jLabelFondo.setForeground(new java.awt.Color(51, 0, 51));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo12.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAActionPerformed

    private void textoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCActionPerformed

    private void textoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDActionPerformed

    private void textoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEActionPerformed

    private void textoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
                           double B=0;
		           double A =Integer.parseInt(textoA.getText()); 
		           double C =Integer.parseInt(textoC.getText());
		           double D =Integer.parseInt(textoD.getText());
		           double E =Integer.parseInt(textoE.getText());
		           double F =Integer.parseInt(textoF.getText());
                           //img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hk.gif")));
                           //img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/h1.gif")));
                           //img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/h2.gif")));
                           //img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/h3.gif")));
                           //img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/h4.gif")));
                           //img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/h5.gif")));
		           egeneral.setText("La funcion introducida es:("+A+")x²+("+B+")xy+("+C+")y²+("+D+")x+("+E+")y+("+F+")=0");//despliega la funcion en su forma general                    
                           String rf= artificio(A,B,C,D,E,F);				//Llama a la funcion que va a analizar la funcion
		   	   rf=rf.replace("\n","<p>");
                           resultado.setText("<html>"+rf+"<html>");
    }//GEN-LAST:event_botonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ventana v2=new ventana();
        //v2.dispose();
        info info=new info();
        info.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel egeneral;
    private javax.swing.JLabel igual;
    private javax.swing.JLabel img;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelFes;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIco;
    private javax.swing.JLabel jLabelInstruccion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField textoA;
    private javax.swing.JTextField textoC;
    private javax.swing.JTextField textoD;
    private javax.swing.JTextField textoE;
    private javax.swing.JTextField textoF;
    private javax.swing.JLabel variablex;
    private javax.swing.JLabel variablexc;
    private javax.swing.JLabel variabley;
    private javax.swing.JLabel variableyc;
    // End of variables declaration//GEN-END:variables
}

