/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;
import Metodos.Falsaposicion;
import Metodos.LeerFuncion;
import Metodos.Newton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FALSAPOSICIONVISTA extends javax.swing.JInternalFrame {
    String Memoria1;
    String Memoria2;
    String Operacion;

    /**
     * Creates new form NEWTONVISTA
     */
    public FALSAPOSICIONVISTA() {
        initComponents();
                this.destino.setVisible(false);
                this.destino1.setVisible(false);
                this.Resultado.setVisible(false);
                this.Resultado5.setVisible(false);
                this.tolerancia.setVisible(false);
                this.titulotolerancia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        titulotolerancia = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        Cal = new javax.swing.JButton();
        destino = new javax.swing.JTextField();
        txtintervaloa = new javax.swing.JTextField();
        tolerancia = new javax.swing.JTextField();
        txtfuncion = new javax.swing.JTextField();
        btnseno6 = new javax.swing.JButton();
        Potencia = new javax.swing.JButton();
        btnseno5 = new javax.swing.JButton();
        txtintervalob = new javax.swing.JTextField();
        Titulo5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnsalir = new javax.swing.JButton();
        Resultado5 = new javax.swing.JLabel();
        destino1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        Titulo.setText("FALSA POSICIÓN");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 11, 314, 50));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setForeground(new java.awt.Color(102, 153, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo1.setBackground(new java.awt.Color(0, 0, 0));
        Titulo1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Titulo1.setText("FUNCION");

        titulotolerancia.setBackground(new java.awt.Color(0, 0, 0));
        titulotolerancia.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        titulotolerancia.setText("ERROR");

        Titulo2.setBackground(new java.awt.Color(0, 0, 0));
        Titulo2.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Titulo2.setText("X             Y");

        Resultado.setBackground(new java.awt.Color(0, 0, 0));
        Resultado.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Resultado.setText("ITERACIONES");

        Cal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/6.jpg"))); // NOI18N
        Cal.setText("CALCULAR");
        Cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalActionPerformed(evt);
            }
        });

        destino.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoActionPerformed(evt);
            }
        });
        destino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                destinoKeyTyped(evt);
            }
        });

        txtintervaloa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtintervaloa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtintervaloaKeyTyped(evt);
            }
        });

        tolerancia.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tolerancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toleranciaKeyTyped(evt);
            }
        });

        txtfuncion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtfuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfuncionActionPerformed(evt);
            }
        });

        btnseno6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnseno6.setText("(");
        btnseno6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseno6ActionPerformed(evt);
            }
        });

        Potencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Potencia.setText("^");
        Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotenciaActionPerformed(evt);
            }
        });

        btnseno5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnseno5.setText(")");
        btnseno5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseno5ActionPerformed(evt);
            }
        });

        txtintervalob.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtintervalob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtintervalobKeyTyped(evt);
            }
        });

        Titulo5.setBackground(new java.awt.Color(0, 0, 0));
        Titulo5.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Titulo5.setText("Escoja la");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPCION", "ITERACION", "RAIZ EXACTA", "ERROR" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/borrar.jpg"))); // NOI18N
        btnsalir.setText("BORRAR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        Resultado5.setBackground(new java.awt.Color(0, 0, 0));
        Resultado5.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Resultado5.setText("RAIZ");

        destino1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        destino1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                destino1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(btnseno6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnseno5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(txtfuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(Resultado5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(destino1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(titulotolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtintervaloa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtintervalob, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(Cal)
                        .addGap(120, 120, 120))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo5))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Potencia)
                            .addComponent(btnseno6)
                            .addComponent(btnseno5))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulotolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtintervaloa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtintervalob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Resultado5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(destino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalir)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(255, 153, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnseno6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseno6ActionPerformed
        // TODO add your handling code here:
        if(!this.txtfuncion.getText().equals("")){
            Memoria1=txtfuncion.getText();
            Operacion="(";
            txtfuncion.setText(txtfuncion.getText()+"(");
        }
    }//GEN-LAST:event_btnseno6ActionPerformed

    private void PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaActionPerformed
        // TODO add your handling code here:
        if(!this.txtfuncion.getText().equals("")){
            Memoria1=txtfuncion.getText();
            Operacion="^";
            txtfuncion.setText(txtfuncion.getText()+"^");
        }
    }//GEN-LAST:event_PotenciaActionPerformed

    private void btnseno5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseno5ActionPerformed
        if(!this.txtfuncion.getText().equals("")){
            Memoria1=txtfuncion.getText();
            Operacion=")";
            txtfuncion.setText(txtfuncion.getText()+")");
        }
    }//GEN-LAST:event_btnseno5ActionPerformed

    private void txtfuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfuncionActionPerformed

    private void CalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalActionPerformed
        // TODO add your handling code here:
                if(this.jComboBox1.getSelectedIndex()==1){
                    try{
                        LeerFuncion Ecuacion=new LeerFuncion(this.txtfuncion.getText());
                        
                        double ya =Double.valueOf(this.txtintervaloa.getText());
                        
                        double yb=Double.valueOf(this.txtintervalob.getText());
                        
                        double E=0;//Double.valueOf(this.tolerancia.getText());
                        
                        double ciclos=Double.valueOf(this.destino.getText());
                        
                        Falsaposicion listo=new Falsaposicion( Ecuacion, ya, yb, E, jTable1, ciclos);
                        
                        listo.FalsaPosicionIte(ciclos);
                    
                    }catch(NumberFormatException e ){
                        JOptionPane.showMessageDialog(null, "Llene toda la informacion");
                    }
                } if(this.jComboBox1.getSelectedIndex()==2){
                    try{
                        LeerFuncion Ecuacion=new LeerFuncion(this.txtfuncion.getText());
                        
                        double ya =Double.valueOf(this.txtintervaloa.getText());
                        
                        double yb=Double.valueOf(this.txtintervalob.getText());
                        
                        double E=Double.valueOf(this.tolerancia.getText());
                        
                        double ciclos=Double.valueOf(this.destino1.getText());
                        
                        Falsaposicion listo=new Falsaposicion( Ecuacion, ya, yb, E, jTable1, ciclos);
                        
                        listo.FalsaPosicionRaiz(ciclos);
                    
                    }catch(NumberFormatException e ){
                        JOptionPane.showMessageDialog(null, "Llene toda la informacion");
                    }
                }if(this.jComboBox1.getSelectedIndex()==3){
                    try{
                        LeerFuncion Ecuacion=new LeerFuncion(this.txtfuncion.getText());
                        
                        double ya =Double.valueOf(this.txtintervaloa.getText());
                        
                        double yb=Double.valueOf(this.txtintervalob.getText());
                        
                        double E=Double.valueOf(this.tolerancia.getText());
                        
                        double ciclos=0;//Double.valueOf(this.destino.getText());
                        
                        Falsaposicion listo=new Falsaposicion( Ecuacion, ya, yb, E, jTable1, ciclos);
                        
                        listo.FalsaPosicionError(E);
                    
                    }catch(NumberFormatException e ){
                        JOptionPane.showMessageDialog(null, "Llene toda la informacion");
                    }
                }



    }//GEN-LAST:event_CalActionPerformed

    private void destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
           if(this.jComboBox1.getSelectedIndex()==1){
            this.destino.setVisible(true);              
            this.Resultado.setVisible(true);
            this.destino1.setVisible(false);
            this.Resultado5.setVisible(false);
            this.tolerancia.setVisible(false);
            this.titulotolerancia.setVisible(false);
            
                          
        }else if(this.jComboBox1.getSelectedIndex()==2){
            this.destino1.setVisible(true);
            this.Resultado5.setVisible(true);
            this.destino.setVisible(false);
            this.Resultado.setVisible(false);
            this.tolerancia.setVisible(true);
            this.titulotolerancia.setVisible(true);
        }else if(this.jComboBox1.getSelectedIndex()==0){
            this.destino1.setVisible(false);
            this.Resultado5.setVisible(false);
            this.destino.setVisible(false);
            this.Resultado.setVisible(false);
            this.tolerancia.setVisible(false);
            this.titulotolerancia.setVisible(false);
        }else if(this.jComboBox1.getSelectedIndex()==3){
            this.destino.setVisible(false);              
            this.Resultado.setVisible(false);
            this.destino1.setVisible(false);
            this.Resultado5.setVisible(false);
            this.tolerancia.setVisible(true);
            this.titulotolerancia.setVisible(true);
            
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.destino.setText(" ");
        this.destino1.setText(" ");
        this.tolerancia.setText(" ");
        this.txtfuncion.setText(" ");
        this.txtintervaloa.setText(" ");
        this.txtintervalob.setText(" ");

        this.destino.setVisible(false);
        this.destino1.setVisible(false);
        this.Resultado5.setVisible(false);
        this.Resultado.setVisible(false);

        DefaultTableModel a = (DefaultTableModel) this.jTable1.getModel();
        while (a.getRowCount() > 0) {
            a.removeRow(0);
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void toleranciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toleranciaKeyTyped
        // TODO add your handling code here:
           Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            if (c != '.') {
                evt.consume();
            }

            if (c == '.') {
                if (this.tolerancia.getText().indexOf('.') != -1) {
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_toleranciaKeyTyped

    private void txtintervaloaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtintervaloaKeyTyped
        // TODO add your handling code here:
                        Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            if (c < '-' || c > '.') {
                evt.consume();
            }

            if (c == '.') {
                if (this.txtintervaloa.getText().indexOf('.') != -1) {
                    evt.consume();
                }
            }

            if (c == '-') {
                if (this.txtintervaloa.getText().indexOf('-') != -1) {
                    evt.consume();
                }
            }
        }

    }//GEN-LAST:event_txtintervaloaKeyTyped

    private void txtintervalobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtintervalobKeyTyped
        // TODO add your handling code here:
                        Character c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            if (c < '-' || c > '.') {
                evt.consume();
            }

            if (c == '.') {
                if (this.txtintervalob.getText().indexOf('.') != -1) {
                    evt.consume();
                }
            }

            if (c == '-') {
                if (this.txtintervalob.getText().indexOf('-') != -1) {
                    evt.consume();
                }
            }
        }

    }//GEN-LAST:event_txtintervalobKeyTyped

    private void destinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destinoKeyTyped
        // TODO add your handling code here:
                Character c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }

    }//GEN-LAST:event_destinoKeyTyped

    private void destino1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destino1KeyTyped
        // TODO add your handling code here:
                        Character c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }

    }//GEN-LAST:event_destino1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cal;
    private javax.swing.JButton Potencia;
    private javax.swing.JLabel Resultado;
    private javax.swing.JLabel Resultado5;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnseno5;
    private javax.swing.JButton btnseno6;
    private javax.swing.JTextField destino;
    private javax.swing.JTextField destino1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titulotolerancia;
    private javax.swing.JTextField tolerancia;
    private javax.swing.JTextField txtfuncion;
    private javax.swing.JTextField txtintervaloa;
    private javax.swing.JTextField txtintervalob;
    // End of variables declaration//GEN-END:variables
}
