/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Usuario
 */
public class MenuS extends javax.swing.JFrame {
    NEWTONVISTA  APA;
     SECANTEVISTA  APE;
     FALSAPOSICIONVISTA API;
     BISECCIONVISTA APO;
   
    /**
     * Creates new form MenuS
     */
    public MenuS() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JButton();
        btnregistroP = new javax.swing.JButton();
        btnregistroHistorial = new javax.swing.JButton();
        btncita = new javax.swing.JButton();
        btnvercita = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuSistema = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        desktopPane.setMinimumSize(new java.awt.Dimension(40, 33));

        BtnSalir.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/salirMenu.jpg"))); // NOI18N
        BtnSalir.setText("SALIR");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnSalir)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(580, 500, 160, 70);

        btnregistroP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnregistroP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/2_1.jpg"))); // NOI18N
        btnregistroP.setText("MÉTODO DE BISECCIÓN");
        btnregistroP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroPActionPerformed(evt);
            }
        });
        desktopPane.add(btnregistroP);
        btnregistroP.setBounds(230, 110, 310, 80);

        btnregistroHistorial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnregistroHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/3.jpg"))); // NOI18N
        btnregistroHistorial.setText("MÉTODO DE NEWTON");
        btnregistroHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroHistorialActionPerformed(evt);
            }
        });
        desktopPane.add(btnregistroHistorial);
        btnregistroHistorial.setBounds(230, 250, 310, 80);

        btncita.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btncita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/4.jpg"))); // NOI18N
        btncita.setText("MÉTODO DE LA FALSA POSICIÓN");
        btncita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncitaActionPerformed(evt);
            }
        });
        desktopPane.add(btncita);
        btncita.setBounds(650, 110, 400, 80);

        btnvercita.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnvercita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/5.gif"))); // NOI18N
        btnvercita.setText("MÉTODO DE LA SECANTE");
        btnvercita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvercitaActionPerformed(evt);
            }
        });
        desktopPane.add(btnvercita);
        btnvercita.setBounds(690, 250, 330, 80);

        jButton1.setText("GRAFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton1);
        jButton1.setBounds(510, 380, 280, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/1_1.jpg"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(0, -30, 1390, 750);

        menuBar.setBackground(new java.awt.Color(51, 153, 255));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setToolTipText("");

        MenuSistema.setMnemonic('f');
        MenuSistema.setText("SISTEMA");

        exitMenuItem.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("SALIR");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        MenuSistema.add(exitMenuItem);

        menuBar.add(MenuSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnregistroPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroPActionPerformed
        // TODO add your handling code here:
          APO= new BISECCIONVISTA();
         this.desktopPane.add(APO);// TODO add your handling code here:
         APO.show();
       
    }//GEN-LAST:event_btnregistroPActionPerformed

    private void btnregistroHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroHistorialActionPerformed
        // TODO add your handling code here:
          APA= new NEWTONVISTA();
         this.desktopPane.add(APA);// TODO add your handling code here:
         APA.show();
       
    }//GEN-LAST:event_btnregistroHistorialActionPerformed

    private void btncitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncitaActionPerformed
        // TODO add your handling code here:
          API= new  FALSAPOSICIONVISTA();
         this.desktopPane.add(API);// TODO add your handling code here:
         API.show();
       
    }//GEN-LAST:event_btncitaActionPerformed

    private void btnvercitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvercitaActionPerformed
        // TODO add your handling code here:
          APE= new SECANTEVISTA();
         this.desktopPane.add(APE);// TODO add your handling code here:
         APE.show();
       
    }//GEN-LAST:event_btnvercitaActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          myFrame aplicacion = new myFrame();
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JMenu MenuSistema;
    private javax.swing.JButton btncita;
    private javax.swing.JButton btnregistroHistorial;
    private javax.swing.JButton btnregistroP;
    private javax.swing.JButton btnvercita;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
